# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc0088c0e75b623acf51f463599c1b7f42b1f04eb00f28af4c7b9c22697f30e93a1c295455219a4cd8685a806e40c80fa29d4fa920d6f5542691f5022e9ea16c

test:
  secret_key_base: 915eb97e4acd51279be949603ebbe31ff87bc1a5023ab37f4f3a7c8ada5a30b0a4f9046da8c0e520a241dffaef516f5075354d6125291f58444a2138f9a34d0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
